name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Suggested API
      description: If applicable, show how the API might look.
      render: typescript
      placeholder: |
        // Example usage
        const result = await scrape(url, {
          newFeature: true,
        });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: I've tried...

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Which part of scrapex does this relate to?
      options:
        - Core scraping
        - Content normalization
        - Embeddings
        - RSS/Atom parsing
        - LLM integration
        - Extractors
        - URL utilities
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
